### PR TITLE
add stage for creating s3 bucket to store dashboard

### PR DESCRIPTION
**Pull request by stein321**

### CODE REVIEW

**Comment by stein321** [comment]
need to add aws creds to environment variables and use a variable key to avoid collisions

**Review by jphayes — APPROVED** [review]
@stein321 consider adding `-no-color` to the terraform commands to avoid getting funky output in the logs. Otherwise looks good.

**Review by RobertKelly — CHANGES_REQUESTED** [review]
Let's get the slack messages in for the new stage.  If it takes more than a few seconds to create put it at the end and add a message that it will take n# of minutes

**Comment by stein321** [comment]
@RobertKelly creation can take a minute and destroy can take 40seconds

**Review by steeeveo — APPROVED** [review]
I see the infra creation stage added, and the finalization message moved to the post block; looks good.

**Review by RobertKelly — APPROVED** [review]

**Pull request merged**
